<template><div><h1 id="_4-ray-tracing" tabindex="-1"><a class="header-anchor" href="#_4-ray-tracing" aria-hidden="true">#</a> 4 Ray Tracing</h1>
<p>One of the basic tasks of computer graphics is rendering three-dimensional objects: taking a scene, or model, composed of many geometric objects arranged in 3D space and producing a 2D image that shows the objects as viewed from a particular viewpoint. It is the same operation that has been done for centuries by architects and engineers creating drawings to communicate their designs to others.</p>
<p>Fundamentally, rendering is a process that takes as its input a set of objects and produces as its output an array of pixels. One way or another, rendering involves considering how each object contributes to each pixel; it can be organized in two general ways. In object-order rendering, each object is considered in turn, and for each object all the pixels that it inﬂuences are found and updated. In imageorder rendering, each pixel is considered in turn, and for each pixel all the objects that inﬂuence it are found and the pixel value is computed. You can think of the difference in terms of the nesting of loops: in image-order rendering the “for each pixel” loop is on the outside, whereas in object-order rendering the “for each object” loop is on the outside.</p>
<p>Image-order and object-order rendering approaches can compute exactly the same images, but they lend themselves to computing different kinds of effects and have quite different performance characteristics. We’ll explore the comparative strengths of the approaches in Chapter 8 after we have discussed them both, but, broadly speaking, image-order rendering is simpler to get working and more ﬂexible in the effects that can be produced, and usually (though not always) takes much more execution time to produce a comparable image.</p>
<p>Ray tracing is an image-order algorithm for making renderings of 3D scenes, and we’ll consider it ﬁrst because it’s possible to get a ray tracer working without developing any of the mathematical machinery that’s used for object-order rendering.</p>
<h2 id="_4-1-the-basic-ray-tracing-algorithm" tabindex="-1"><a class="header-anchor" href="#_4-1-the-basic-ray-tracing-algorithm" aria-hidden="true">#</a> 4.1 The Basic Ray-Tracing Algorithm</h2>
<p>A ray tracer works by computing one pixel at a time, and for each pixel the basic task is to ﬁnd the object that is seen at that pixel’s position in the image. Each pixel “looks” in a different direction, and any object that is seen by a pixel must intersect the viewing ray, a line that emanates from the viewpoint in the direction that pixel is looking. The particular object we want is the one that intersects the viewing ray nearest the camera, since it blocks the view of any other objects behind it. Once that object is found, a shading computation uses the intersection point, surface normal, and other information (depending on the desired type of rendering) to determine the color of the pixel. This is shown in Figure 4.1, where the ray intersects two triangles, but only the ﬁrst triangle hit, <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>T</mi><mn>2</mn></msub></mrow><annotation encoding="application/x-tex">T_2</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8333em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.13889em;">T</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3011em;"><span style="top:-2.55em;margin-left:-0.1389em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> , is shaded.</p>
<p>A basic ray tracer therefore has three parts:</p>
<h2 id="_4-2-perspective" tabindex="-1"><a class="header-anchor" href="#_4-2-perspective" aria-hidden="true">#</a> 4.2 Perspective</h2>
<h2 id="_4-3-computing-viewing-rays" tabindex="-1"><a class="header-anchor" href="#_4-3-computing-viewing-rays" aria-hidden="true">#</a> 4.3 Computing Viewing Rays</h2>
<h2 id="_4-4-ray-object-intersection" tabindex="-1"><a class="header-anchor" href="#_4-4-ray-object-intersection" aria-hidden="true">#</a> 4.4 Ray-Object Intersection</h2>
<h2 id="_4-5-shading" tabindex="-1"><a class="header-anchor" href="#_4-5-shading" aria-hidden="true">#</a> 4.5 Shading</h2>
<h2 id="_4-6-a-ray-tracing-program" tabindex="-1"><a class="header-anchor" href="#_4-6-a-ray-tracing-program" aria-hidden="true">#</a> 4.6 A Ray-Tracing Program</h2>
<h2 id="_4-7-shadows" tabindex="-1"><a class="header-anchor" href="#_4-7-shadows" aria-hidden="true">#</a> 4.7 Shadows</h2>
<h2 id="_4-8-ideal-specular-reflection" tabindex="-1"><a class="header-anchor" href="#_4-8-ideal-specular-reflection" aria-hidden="true">#</a> 4.8 Ideal Specular Reﬂection</h2>
<h2 id="_4-9-historical-notes" tabindex="-1"><a class="header-anchor" href="#_4-9-historical-notes" aria-hidden="true">#</a> 4.9 Historical Notes</h2>
</div></template>


